[workspace]
members = [
  # core
  "leptos",
  "leptos_dom",
  "leptos_core",
  "leptos_macro",
  "leptos_reactive",
  "leptos_server",

  # libraries
  "meta",
  "router",
]

exclude = ["examples/*", "benchmarks"]


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
