[workspace]

[package]
name = "counter-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_log = "0.2"
leptos = { path = "../../../leptos", default-features = false, features = [
  "hydrate",
  "serde",
] }
counter-isomorphic = { path = "../counter", default-features = false, features = [
  "hydrate",
] }
log = "0.4"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
