[package]
name = "leptos_dom"
version = "0.0.11"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "DOM operations for the Leptos web framework."

[dependencies]
futures = { version = "0.3", optional = true }
html-escape = { version = "0.2", optional = true }
js-sys = "0.3"
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.11" }
serde_json = { version = "1", optional = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.31"
log = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "Attr",
  "console",
  "Comment",
  "CssStyleDeclaration",
  "CustomEvent",
  "CustomEventInit",
  "Document",
  "DocumentFragment",
  "DomStringMap",
  "DomTokenList",
  "Element",
  "Event",
  "EventTarget",
  "HtmlCollection",
  "HtmlDivElement",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlTemplateElement",
  "KeyboardEvent",
  "Location",
  "MutationObserver",
  "NamedNodeMap",
  "Node",
  "NodeList",
  "Performance",
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
  "Storage",
  "Text",
  "TreeWalker",
  "Window",
]

[features]
csr = ["leptos_reactive/csr"]
hydrate = ["leptos_reactive/hydrate"]
ssr = [
  "leptos_reactive/ssr",
  "dep:futures",
  "dep:html-escape",
  "dep:serde_json",
]
stable = ["leptos_reactive/stable"]

[package.metadata.cargo-all-features]
# mutually exclusive features
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["hydrate", "ssr"]]

# No need to test optional dependencies as they are enabled by the ssr feature
denylist = ["futures", "html-escape", "serde_json"]
