[package]
name = "leptos"
version = "0.0.11"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Leptos is a full-stack, isomorphic Rust web framework leveraging fine-grained reactivity to build declarative user interfaces."
readme = "../README.md"

[dependencies]
leptos_core = { path = "../leptos_core", default-features = false, version = "0.0.11" }
leptos_dom = { path = "../leptos_dom", default-features = false, version = "0.0.11" }
leptos_macro = { path = "../leptos_macro", default-features = false, version = "0.0.11" }
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.11" }
leptos_server = { path = "../leptos_server", default-features = false, version = "0.0.11" }

[features]
default = ["csr", "serde"]
csr = [
  "leptos_core/csr",
  "leptos_dom/csr",
  "leptos_macro/csr",
  "leptos_reactive/csr",
  "leptos_server/csr",
]
hydrate = [
  "leptos_core/hydrate",
  "leptos_dom/hydrate",
  "leptos_macro/hydrate",
  "leptos_reactive/hydrate",
  "leptos_server/hydrate",
]
ssr = [
  "leptos_core/ssr",
  "leptos_dom/ssr",
  "leptos_macro/ssr",
  "leptos_reactive/ssr",
  "leptos_server/ssr",
]
stable = [
  "leptos_core/stable",
  "leptos_dom/stable",
  "leptos_macro/stable",
  "leptos_reactive/stable",
  "leptos_server/stable",
]
serde = ["leptos_reactive/serde"]
serde-lite = ["leptos_reactive/serde-lite"]
miniserde = ["leptos_reactive/miniserde"]

[package.metadata.cargo-all-features]
# mutually exclusive features
skip_feature_sets = [
  ["csr", "ssr"],
  ["csr", "hydrate"],
  ["hydrate", "ssr"],
  ["serde", "serde-lite"], 
  ["serde-lite", "miniserde"],
  ["serde", "miniserde"]
]
denylist = ["stable"]