[package]
name = "leptos_server"
version = "0.0.11"
edition = "2021"

[dependencies]
leptos_dom = { path = "../leptos_dom", default-features = false, version = "0.0.11" }
leptos_reactive = { path = "../leptos_reactive", default-features = false, version = "0.0.11" }
async-trait = "0.1"
form_urlencoded = "1"
gloo-net = { version = "0.2", optional = true }
lazy_static = "1"
linear-map = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[features]
csr = ["leptos_dom/csr", "leptos_reactive/csr", "dep:gloo-net"]
hydrate = ["leptos_dom/hydrate", "leptos_reactive/hydrate", "dep:gloo-net"]
ssr = ["leptos_dom/ssr", "leptos_reactive/ssr"]
stable = ["leptos_dom/stable", "leptos_reactive/stable"]

[package.metadata.cargo-all-features]
# mutually exclusive features
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["hydrate", "ssr"]]

# No need to test optional dependencies as they are enabled by the ssr & hydrate feature
denylist = ["gloo-net"]
